on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: debian-latest
    outputs:
      jar-path: ${{ steps.set-jar-path.outputs.jar-path }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3

        with:
          distribution: temurin
          java-version: 24

      - name: Run tests
        run: ./gradlew --quiet test

      - name: Clean
        run: ./gradlew --quiet clean

      - name: Build with Gradle
        run: ./gradlew --quiet bootJar

      - name: Save JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: homework_50.jar
          path: build/libs/homework_50-1.0-SNAPSHOT.jar

  build-and-push-docker:
    needs: build-and-test
    runs-on: debian-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: homework_50.jar
          path: build/libs

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/homework_50:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/homework_50:latest

  deploy:
    needs: build-and-push-docker
    runs-on: debian-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ VM_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/homework_50:latest
            docker stop homework_50 || true
            docker rm homework_50 || true
            docker run -d --name homework_50 -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/homework_50:latest
